# Generated by Django 3.0.7 on 2020-10-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
